# -*- coding: utf-8 -*-
lines = [
"import React, { useState, useEffect } from 'react';",
"import axios from 'axios';",
"",
"const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000';",
"",
"function ParamsSearch({ onResults, onError, setLoading }) {",
"  const [params, setParams] = useState({",
"    type: '', min_price: '', max_price: '',",
"    width: '', length: '', height: '',",
"    style: '', materials: '', colors: '', brand: ''",
"  });",
"  const [types, setTypes] = useState([]);",
"  const [styles, setStyles] = useState([]);",
"  const [colors, setColors] = useState([]);",
"  const [materials, setMaterials] = useState([]);",
"",
"  useEffect(() => {",
"    axios.get(`${API_URL}/api/furniture/types`).then(r => setTypes(r.data.types)).catch(() => {});",
"    axios.get(`${API_URL}/api/furniture/styles`).then(r => setStyles(r.data.styles)).catch(() => {});",
"    axios.get(`${API_URL}/api/furniture/colors`).then(r => setColors(r.data.colors)).catch(() => {});",
"    axios.get(`${API_URL}/api/furniture/materials`).then(r => setMaterials(r.data.materials)).catch(() => {});",
"  }, []);",
"",
"  const handleChange = (e) => setParams({ ...params, [e.target.name]: e.target.value });",
"",
"  const handleSubmit = async (e) => {",
"    e.preventDefault();",
"    setLoading(true);",
"    try {",
"      const response = await axios.post(`${API_URL}/api/search/params`, params);",
"      onResults(response.data.results);",
"    } catch (err) {",
"      onError(err);",
"    } finally {",
"      setLoading(false);",
"    }",
"  };",
"",
"  return (",
'    <div className="params-search">',
'      <form onSubmit={handleSubmit}>',
'        <div className="form-grid">',
'          <div className="form-group">',
'            <label>\u0422\u0438\u043f \u043c\u0435\u0431\u0435\u043b\u0438</label>',
'            <select name="type" value={params.type} onChange={handleChange}>',
'              <option value="">\u041b\u044e\u0431\u043e\u0439</option>',
'              {types.map(t => <option key={t} value={t}>{t}</option>)}',
'            </select>',
'          </div>',
'          <div className="form-group">',
'            <label>\u0421\u0442\u0438\u043b\u044c</label>',
'            <select name="style" value={params.style} onChange={handleChange}>',
'              <option value="">\u041b\u044e\u0431\u043e\u0439</option>',
'              {styles.map(s => <option key={s} value={s}>{s}</option>)}',
'            </select>',
'          </div>',
'          <div className="form-group">',
'            <label>\u0426\u0432\u0435\u0442</label>',
'            <select name="colors" value={params.colors} onChange={handleChange}>',
'              <option value="">\u041b\u044e\u0431\u043e\u0439</option>',
'              {colors.map(c => <option key={c} value={c}>{c}</option>)}',
'            </select>',
'          </div>',
'          <div className="form-group">',
'            <label>\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b</label>',
'            <select name="materials" value={params.materials} onChange={handleChange}>',
'              <option value="">\u041b\u044e\u0431\u043e\u0439</option>',
'              {materials.map(m => <option key={m} value={m}>{m}</option>)}',
'            </select>',
'          </div>',
'          <div className="form-group">',
'            <label>\u0426\u0435\u043d\u0430 \u043e\u0442 (\u20bd)</label>',
'            <input type="number" name="min_price" value={params.min_price} onChange={handleChange} placeholder="0" />',
'          </div>',
'          <div className="form-group">',
'            <label>\u0426\u0435\u043d\u0430 \u0434\u043e (\u20bd)</label>',
'            <input type="number" name="max_price" value={params.max_price} onChange={handleChange} placeholder="100000" />',
'          </div>',
'          <div className="form-group">',
'            <label>\u0428\u0438\u0440\u0438\u043d\u0430 \u0434\u043e (\u0441\u043c)</label>',
'            <input type="number" name="width" value={params.width} onChange={handleChange} placeholder="200" />',
'          </div>',
'          <div className="form-group">',
'            <label>\u0414\u043b\u0438\u043d\u0430 \u0434\u043e (\u0441\u043c)</label>',
'            <input type="number" name="length" value={params.length} onChange={handleChange} placeholder="200" />',
'          </div>',
'          <div className="form-group">',
'            <label>\u0412\u044b\u0441\u043e\u0442\u0430 \u0434\u043e (\u0441\u043c)</label>',
'            <input type="number" name="height" value={params.height} onChange={handleChange} placeholder="100" />',
'          </div>',
'          <div className="form-group">',
'            <label>\u0411\u0440\u0435\u043d\u0434</label>',
'            <input type="text" name="brand" value={params.brand} onChange={handleChange} placeholder="hoff, ikea..." />',
'          </div>',
'        </div>',
'        <p style={{ color: "#888", fontSize: "0.85rem", marginBottom: "0.75rem" }}>',
'          \u0414\u043b\u044f \u043f\u043e\u0438\u0441\u043a\u0430 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e \u0432\u0432\u0435\u0434\u0438\u0442\u0435 \u043c\u0438\u043d\u0438\u043c\u0443\u043c \u043e\u0434\u0438\u043d \u043f\u0440\u0438\u0437\u043d\u0430\u043a',
'        </p>',
'        <button type="submit" className="search-btn">\u041d\u0430\u0439\u0442\u0438</button>',
'      </form>',
'    </div>',
'  );',
'}',
'',
'export default ParamsSearch;',
]

with open('frontend/src/components/ParamsSearch.js', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('OK')
